### ISSUE TITLE
TypeError: unsupported operand type(s) for ^: 'str' and 'str'

### ISSUE THREAD

**Issue by kevin39** [mkorz/b618reboot#5]
Hi,
Any idea about my error ?
I'm having a B715s-23c and I'm trying to use your script :)

```$ python reboot_router.py
Traceback (most recent call last):
  File "reboot_router.py", line 115, in <module>
    sys.exit(main())
  File "reboot_router.py", line 111, in main
    reboot(client, ROUTER, USER, PASSWORD)
  File "reboot_router.py", line 100, in reboot
    verification_token = login(client, server, user, password)
  File "reboot_router.py", line 84, in login
    clientnonce, servernonce, password, salt, iterations).decode('UTF-8')
  File "reboot_router.py", line 53, in get_client_proof
    client_proof.append(client_key_digest[i] ^ signature_digest[i])
TypeError: unsupported operand type(s) for ^: 'str' and 'str'```

$ python --version
Python 2.7.12

**Comment by kevin39** [comment]
Oh... It works fine with Python3. 

Thank you :D
